version: "syntax-highlight-theme.{build}"

os: Visual Studio 2017

platform:
  - x64

branches:
  only:
    - master

skip_non_tags: true

init:
  - npm --version

install:
  - npm update
  - npm install -g vsce

build_script:
  - vsce package

after_build:
  - vsce publish -p $env:VSCode-Market-Token
  - appveyor PushArtifact *.vsix
