version: 'syntax-highlight-theme.{build}'

os: Visual Studio 2017

platform:
    - x64
    
branches:
  only:
    - master

skip_tags: false

init:
    - npm --version

install:
    - npm update
    - npm install -g vsce 

build_script:
    - vsce package

after_build:
    - vsce publish -p ihrya2gw77tys3mo7pjjucwovfvi35wn5xppar3yvy4i3e6p67va