name: build
on:
  push:
    branches:
      - dev

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install vsce
      run: |
        npm update
        npm install -g vsce
        npx vsce package
        